<?php

function footmali_instant_articles_menu() {
  $items['instant_articles_dev.rss'] = array(
    'title' => 'Instant Articles Dev',
    'page callback' => 'footmali_instant_articles_dev_feed',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['instant_articles_prod.rss'] = array(
    'title' => 'Instant Articles Prod',
    'page callback' => 'footmali_instant_articles_prod_feed',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function footmali_instant_articles_dev_feed() {
  header('Content-Type: text/xml; charset=utf-8', TRUE);

  $nodes = footmali_instant_articles_articles();
  ?>
    <rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
      <channel>
        <title>Footmali.com</title>
        <link>http://www.footmali.com/</link>
        <description>
          Les actualités sur les Aigles et les Aiglons du Mali et Championnat du Mali.
        </description>
        <language>fr-fr</language>
        <lastBuildDate><?php echo date(DateTime::ISO8601); ?></lastBuildDate>
        <?php foreach($nodes as $node): ?>
          <item>
            <title><?php echo check_plain($node->title); ?></title>
            <link>
              <?php echo url(drupal_get_path_alias(
                "node/" . $node->nid),
                array('absolute' => TRUE
              )); ?>
            </link>
            <guid><?php echo $node->uuid; ?></guid>
            <pubDate><?php echo date('c', $node->created); ?></pubDate>
            <author><?php echo footmali_instant_articles_author($node); ?></author>
            <content:encoded>
              <![CDATA[
              <!doctype html>
              <html lang="fr" prefix="op: http://media.facebook.com/op#">
                <head>
                  <meta charset="utf-8">
                  <link rel="canonical" href="
                  <?php echo url(drupal_get_path_alias(
                    "node/" . $node->nid),
                    array('absolute' => TRUE
                  )); ?>">
                  <meta property="fb:use_automatic_ad_placement" content="true">
                  <meta property="op:markup_version" content="v1.0">
                  <meta property="fb:article_style" content="Footmali Default">
                  <meta property="fb:use_automatic_ad_placement" content="true">
                </head>
                <body>
                  <article>
                    <header>
                    	<section class="op-ad-template">
                    		<figure class="op-ad">
		                        <iframe height="250" width="300">
		                        	  <!-- Include full ad code here -->
		                            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		                            <!-- FB Instant Articles -->
		                            <ins class="adsbygoogle"
		                                 style="display:inline-block;width:300px;height:250px"
		                                 data-ad-client="ca-pub-7538390076513661"
		                                 data-ad-slot="7316411112"></ins>
		                            <script>
		                            (adsbygoogle = window.adsbygoogle || []).push({});
		                            </script>
		                        </iframe>
		                    </figure>
		                    <figure class="op-ad op-ad-default">
		                    	<iframe height="250" width="300">
		                    		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
									<!-- FB Instant Articles 2 -->
									<ins class="adsbygoogle"
									     style="display:inline-block;width:300px;height:250px"
									     data-ad-client="ca-pub-7538390076513661"
									     data-ad-slot="2965643117"></ins>
									<script>
									(adsbygoogle = window.adsbygoogle || []).push({});
									</script>
		                    	</iframe>
		                    </figure>
		                    <figure class="op-ad">
		                    	<iframe height="250" width="300">
		                    		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
									<!-- FB Instant Articles 3 -->
									<ins class="adsbygoogle"
									     style="display:inline-block;width:300px;height:250px"
									     data-ad-client="ca-pub-7538390076513661"
									     data-ad-slot="1349309110"></ins>
									<script>
									(adsbygoogle = window.adsbygoogle || []).push({});
									</script>
		                    	</iframe>
		                    </figure>
                    	</section>

                      <!— Article header goes here -->
                      <figure data-mode=aspect-fit>
                        <?php echo footmali_instant_articles_image('homepage_highlight_carousel', $node->field_image); ?>
                      </figure>

                      <!-- The title shown in your article -->
                      <h1><?php echo check_plain($node->title); ?></h1>

                      <?php if(footmali_instant_articles_category($node)): ?>
                        <!-- A kicker for your article -->
                        <h3 class="op-kicker"><?php echo check_plain(footmali_instant_articles_category($node)); ?></h3>
                      <?php endif; ?>

                      <!-- The author of your article -->
                      <address>
                        <a title="Journalist"><?php echo footmali_instant_articles_author($node); ?></a>
                      </address>

                      <!-- The published and last modified time stamps -->
                      <time class="op-published" dateTime="<?php echo date('c', $node->created); ?>">
                        <?php echo date('j F Y, H:i', $node->created); ?>
                      </time>
                      <time class="op-modified" dateTime="<?php echo date('c', $node->changed); ?>">
                        <?php echo date('j F Y, H:i', $node->changed); ?>
                      </time>
                    </header>

                    <!— Article body goes here -->
                    <?php echo render($node->body[LANGUAGE_NONE][0]['value']); ?>
                    
                    <footer>
                      <ul class="op-related-articles"></ul>
                    </footer>

                    <figure class="op-tracker">
                        <iframe>
                        	<!-- Include full analytics code here -->
                          <script>
                            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

                            ga('create', 'UA-20124674-1', 'auto');
                            ga('require', 'displayfeatures');
                            ga('set', 'campaignSource', 'Facebook');
                            ga('set', 'campaignMedium', 'Social Instant Article');
                            ga('send', 'pageview', {"title": "<?php echo check_plain($node->title); ?>"});

                          </script>
                        </iframe>
                    </figure>
                  </article>
                </body>
              </html>
              ]]>
            </content:encoded>
          </item>
        <?php endforeach; ?>
      </channel>
    </rss>
  <?php
}

function footmali_instant_articles_prod_feed() {
  header('Content-Type: text/xml; charset=utf-8', TRUE);

  $nodes = footmali_instant_articles_articles();
  ?>
    <rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
      <channel>
        <title>Footmali.com</title>
        <link>http://www.footmali.com/</link>
        <description>
          Les actualités sur les Aigles et les Aiglons du Mali et Championnat du Mali.
        </description>
        <language>fr-fr</language>
        <lastBuildDate><?php echo date(DateTime::ISO8601); ?></lastBuildDate>
        <?php foreach($nodes as $node): ?>
          <item>
            <title><?php echo check_plain($node->title); ?></title>
            <link>
              <?php echo url(drupal_get_path_alias(
                "node/" . $node->nid),
                array('absolute' => TRUE
              )); ?>
            </link>
            <guid><?php echo $node->uuid; ?></guid>
            <pubDate><?php echo date('c', $node->created); ?></pubDate>
            <author><?php echo footmali_instant_articles_author($node); ?></author>
            <content:encoded>
              <![CDATA[
              <!doctype html>
              <html lang="fr" prefix="op: http://media.facebook.com/op#">
                <head>
                  <meta charset="utf-8">
                  <link rel="canonical" href="
                  <?php echo url(drupal_get_path_alias(
                    "node/" . $node->nid),
                    array('absolute' => TRUE
                  )); ?>">
                  <meta property="fb:use_automatic_ad_placement" content="true">
                  <meta property="op:markup_version" content="v1.0">
                  <meta property="fb:article_style" content="Footmali Default">
                  <meta property="fb:use_automatic_ad_placement" content="true">
                </head>
                <body>
                  <article>
                    <header>
                    	<section class="op-ad-template">
                    		<figure class="op-ad">
		                        <iframe height="250" width="300">
		                        	  <!-- Include full ad code here -->
		                            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
		                            <!-- FB Instant Articles -->
		                            <ins class="adsbygoogle"
		                                 style="display:inline-block;width:300px;height:250px"
		                                 data-ad-client="ca-pub-7538390076513661"
		                                 data-ad-slot="7316411112"></ins>
		                            <script>
		                            (adsbygoogle = window.adsbygoogle || []).push({});
		                            </script>
		                        </iframe>
		                    </figure>
		                    <figure class="op-ad op-ad-default">
		                    	<iframe height="250" width="300">
		                    		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
									<!-- FB Instant Articles 2 -->
									<ins class="adsbygoogle"
									     style="display:inline-block;width:300px;height:250px"
									     data-ad-client="ca-pub-7538390076513661"
									     data-ad-slot="2965643117"></ins>
									<script>
									(adsbygoogle = window.adsbygoogle || []).push({});
									</script>
		                    	</iframe>
		                    </figure>
		                    <figure class="op-ad">
		                    	<iframe height="250" width="300">
		                    		<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
									<!-- FB Instant Articles 3 -->
									<ins class="adsbygoogle"
									     style="display:inline-block;width:300px;height:250px"
									     data-ad-client="ca-pub-7538390076513661"
									     data-ad-slot="1349309110"></ins>
									<script>
									(adsbygoogle = window.adsbygoogle || []).push({});
									</script>
		                    	</iframe>
		                    </figure>
                    	</section>

                      <!— Article header goes here -->
                      <figure data-mode=aspect-fit>
                        <?php echo footmali_instant_articles_image('homepage_highlight_carousel', $node->field_image); ?>
                      </figure>

                      <!-- The title shown in your article -->
                      <h1><?php echo check_plain($node->title); ?></h1>

                      <?php if(footmali_instant_articles_category($node)): ?>
                        <!-- A kicker for your article -->
                        <h3 class="op-kicker"><?php echo check_plain(footmali_instant_articles_category($node)); ?></h3>
                      <?php endif; ?>

                      <!-- The author of your article -->
                      <address>
                        <a title="Journalist"><?php echo footmali_instant_articles_author($node); ?></a>
                      </address>

                      <!-- The published and last modified time stamps -->
                      <time class="op-published" dateTime="<?php echo date('c', $node->created); ?>">
                        <?php echo date('j F Y, H:i', $node->created); ?>
                      </time>
                      <time class="op-modified" dateTime="<?php echo date('c', $node->changed); ?>">
                        <?php echo date('j F Y, H:i', $node->changed); ?>
                      </time>
                    </header>

                    <!— Article body goes here -->
                    <?php echo render($node->body[LANGUAGE_NONE][0]['value']); ?>
                    
                    <footer>
                      <!— Article footer goes here -->
                       <small>Footmali © <?php echo date('Y'); ?></small>
                    </footer>

                    <figure class="op-tracker">
                        <iframe>
                        	<!-- Include full analytics code here -->
                          <script>
                            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

                            ga('create', 'UA-20124674-1', 'auto');
                            ga('require', 'displayfeatures');
                            ga('set', 'campaignSource', 'Facebook');
                            ga('set', 'campaignMedium', 'Social Instant Article');
                            ga('send', 'pageview', {"title": "<?php echo check_plain($node->title); ?>"});

                          </script>
                        </iframe>
                    </figure>
                  </article>
                </body>
              </html>
              ]]>
            </content:encoded>
          </item>
        <?php endforeach; ?>
      </channel>
    </rss>
  <?php
}

function footmali_instant_articles_articles() {
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'article')
        ->propertyCondition('status', NODE_PUBLISHED)
        ->range(0, 10)
        ->propertyOrderBy('created', 'DESC');

  $result = $query->execute();
  $news_items = array();

  if (isset($result['node'])) {
    $news_items_nids = array_keys($result['node']);
    $news_items += entity_load('node', $news_items_nids);
  }

  return $news_items;
}

function footmali_instant_articles_image($style, $imageEntity){
    $variable = array(
        'style_name' => $style,
        'path' => $imageEntity[LANGUAGE_NONE][0]['uri'],
        'width' => $imageEntity[LANGUAGE_NONE][0]['width'],
        'height' => $imageEntity[LANGUAGE_NONE][0]['height'],
    );
    return theme_image_style($variable);
}

function footmali_instant_articles_author($node){
  $author_data = user_load($node->uid);
  $author = $node->name;
  if(isset($author_data->field_first_name) && isset($author_data->field_last_name)){
      $author = field_get_items('user', $author_data, 'field_first_name')[0]['value'] . ' ';
      $author .= field_get_items('user', $author_data, 'field_last_name')[0]['value'];
  }
  return $author;
}

function footmali_instant_articles_category($node){
  $news_category = '';
  $tid = isset($node->field_category[LANGUAGE_NONE][0]['tid']);
  $taxonomy = taxonomy_term_load($tid);
  if($taxonomy){
      $news_category = $taxonomy->name;
  }

  return $news_category;
}

function footmali_instant_articles_trim_paragraph($string, $your_desired_width) {
    $string = strip_tags($string);
    $parts = preg_split('/([\s\n\r]+)/', $string, null, PREG_SPLIT_DELIM_CAPTURE);
    $parts_count = count($parts);
    $length = 0;
    $last_part = 0;
    for (; $last_part < $parts_count; ++$last_part) {
        $length += strlen($parts[$last_part]);
        if ($length > $your_desired_width) { break; }
    }
    return implode(array_slice($parts, 0, $last_part));
}
