<?php

function footmali_instant_articles_menu() {
  $items['instant_articles_dev.rss'] = array(
    'title' => 'Instant Articles Dev',
    'page callback' => 'footmali_instant_articles_dev_feed',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['instant_articles_prod.rss'] = array(
    'title' => 'Instant Articles Prod',
    'page callback' => 'footmali_instant_articles_prod_feed',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function footmali_instant_articles_dev_feed() {
  header('Content-Type: text/xml; charset=utf-8', TRUE);

  $nodes = footmali_instant_articles_articles();
  ?>
    <rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
      <channel>
        <title>Footmali.com</title>
        <link>http://www.footmali.com/</link>
        <description>
          Les actualités sur les Aigles et les Aiglons du Mali et Championnat du Mali.
        </description>
        <language>fr-fr</language>
        <lastBuildDate><?php echo date(DateTime::ISO8601); ?></lastBuildDate>
        <?php foreach($nodes as $node): ?>
          <item>
            <title><?php echo check_plain($node->title); ?></title>
            <link>
              <?php echo url(drupal_get_path_alias(
                "node/" . $node->nid),
                array('absolute' => TRUE
              )); ?>
            </link>
            <guid><?php echo $node->uuid; ?></guid>
            <pubDate><?php echo date('c', $node->created); ?></pubDate>
            <author><?php echo footmali_instant_articles_author($node); ?></author>
            <content:encoded>
              <![CDATA[
              <!doctype html>
              <html lang="fr" prefix="op: http://media.facebook.com/op#">
                <head>
                  <meta charset="utf-8">
                  <link rel="canonical" href="
                  <?php echo url(drupal_get_path_alias(
                    "node/" . $node->nid),
                    array('absolute' => TRUE
                  )); ?>">
                  <meta property="op:markup_version" content="v1.0">
                  <meta property="fb:article_style" content="Footmali Default">
                  <meta property="fb:use_automatic_ad_placement" content="true">
                </head>
                <body>

                  <!-- Google Tag Manager -->
                  <figure class="op-tracker">
                      <iframe>
                        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
                        })(window,document,'script','dataLayer','GTM-PZ9QB3K');</script>
                      </iframe>
                  </figure>
                  <!-- End Google Tag Manager -->

                  <article>
                    <header>
                      <!— Article header goes here -->
                      <figure data-mode=aspect-fit>
                        <?php echo footmali_instant_articles_image('homepage_highlight_carousel', $node->field_image); ?>
                      </figure>

                      <!-- The title shown in your article -->
                      <h1><?php echo check_plain($node->title); ?></h1>

                      <?php if(footmali_instant_articles_category($node)): ?>
                        <!-- A kicker for your article -->
                        <h3 class="op-kicker"><?php echo check_plain(footmali_instant_articles_category($node)); ?></h3>
                      <?php endif; ?>

                      <!-- The author of your article -->
                      <address>
                        <a title="Journalist"><?php echo footmali_instant_articles_author($node); ?></a>
                      </address>

                      <!-- The published and last modified time stamps -->
                      <time class="op-published" dateTime="<?php echo date('c', $node->created); ?>">
                        <?php echo date('j F Y, H:i', $node->created); ?>
                      </time>
                      <time class="op-modified" dateTime="<?php echo date('c', $node->changed); ?>">
                        <?php echo date('j F Y, H:i', $node->changed); ?>
                      </time>
                    </header>

                    <!— Article body goes here -->
                    <?php echo render($node->body[LANGUAGE_NONE][0]['value']); ?>

                    <figure class="op-ad">
                      <iframe height="300" width="250">
                        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                        <!-- amp_between_article_text_1 -->
                        <ins class="adsbygoogle"
                            style="display:block"
                            data-ad-client="ca-pub-1792676367399829"
                            data-ad-slot="4461304241"
                            data-ad-format="auto"
                            data-full-width-responsive="true"></ins>
                        <script>
                            (adsbygoogle = window.adsbygoogle || []).push({});
                        </script>
                      </iframe>
                    </figure>

                    <figure class="op-ad">
                      <iframe height="300" width="250">
                        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                        <!-- amp_between_article_text_1 -->
                        <ins class="adsbygoogle"
                            style="display:block"
                            data-ad-client="ca-pub-1792676367399829"
                            data-ad-slot="6258791014"
                            data-ad-format="auto"
                            data-full-width-responsive="true"></ins>
                        <script>
                            (adsbygoogle = window.adsbygoogle || []).push({});
                        </script>
                      </iframe>
                    </figure>
                    
                    <footer>
                      <ul class="op-related-articles">
                        <?php $related = false ?>
                        <?php if($related = get_next_article_link($node->nid)): ?>
                        <?php else: ?>
                          <?php $related = get_previous_article_link($node->nid); ?>
                        <?php endif; ?>
                        <li><a href="<?php echo $related; ?>"></a></li>
                      </ul>
                    </footer>
                  </article>
                </body>
              </html>
              ]]>
            </content:encoded>
          </item>
        <?php endforeach; ?>
      </channel>
    </rss>
  <?php
}

function footmali_instant_articles_prod_feed() {
  header('Content-Type: text/xml; charset=utf-8', TRUE);

  $nodes = footmali_instant_articles_articles();
  ?>
    <rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
      <channel>
        <title>Footmali.com</title>
        <link>http://www.footmali.com/</link>
        <description>
          Les actualités sur les Aigles et les Aiglons du Mali et Championnat du Mali.
        </description>
        <language>fr-fr</language>
        <lastBuildDate><?php echo date(DateTime::ISO8601); ?></lastBuildDate>
        <?php foreach($nodes as $node): ?>
          <item>
            <title><?php echo check_plain($node->title); ?></title>
            <link>
              <?php echo url(drupal_get_path_alias(
                "node/" . $node->nid),
                array('absolute' => TRUE
              )); ?>
            </link>
            <guid><?php echo $node->uuid; ?></guid>
            <pubDate><?php echo date('c', $node->created); ?></pubDate>
            <author><?php echo footmali_instant_articles_author($node); ?></author>
            <content:encoded>
              <![CDATA[
              <!doctype html>
              <html lang="fr" prefix="op: http://media.facebook.com/op#">
                <head>
                  <meta charset="utf-8">
                  <link rel="canonical" href="
                  <?php echo url(drupal_get_path_alias(
                    "node/" . $node->nid),
                    array('absolute' => TRUE
                  )); ?>">
                  <meta property="op:markup_version" content="v1.0">
                  <meta property="fb:article_style" content="Footmali Default">
                  <meta property="fb:use_automatic_ad_placement" content="true">
                </head>
                <body>

                  <!-- Google Tag Manager -->
                  <figure class="op-tracker">
                      <iframe>
                        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
                        })(window,document,'script','dataLayer','GTM-PZ9QB3K');</script>
                      </iframe>
                  </figure>
                  <!-- End Google Tag Manager -->

                  <article>
                    <header>
                      <!— Article header goes here -->
                      <figure data-mode=aspect-fit>
                        <?php echo footmali_instant_articles_image('homepage_highlight_carousel', $node->field_image); ?>
                      </figure>

                      <!-- The title shown in your article -->
                      <h1><?php echo check_plain($node->title); ?></h1>

                      <?php if(footmali_instant_articles_category($node)): ?>
                        <!-- A kicker for your article -->
                        <h3 class="op-kicker"><?php echo check_plain(footmali_instant_articles_category($node)); ?></h3>
                      <?php endif; ?>

                      <!-- The author of your article -->
                      <address>
                        <a title="Journalist"><?php echo footmali_instant_articles_author($node); ?></a>
                      </address>

                      <!-- The published and last modified time stamps -->
                      <time class="op-published" dateTime="<?php echo date('c', $node->created); ?>">
                        <?php echo date('j F Y, H:i', $node->created); ?>
                      </time>
                      <time class="op-modified" dateTime="<?php echo date('c', $node->changed); ?>">
                        <?php echo date('j F Y, H:i', $node->changed); ?>
                      </time>
                    </header>

                    <!— Article body goes here -->
                    <?php echo render($node->body[LANGUAGE_NONE][0]['value']); ?>

                    <figure class="op-ad">
                      <iframe height="300" width="250">
                        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                        <!-- amp_between_article_text_1 -->
                        <ins class="adsbygoogle"
                            style="display:block"
                            data-ad-client="ca-pub-1792676367399829"
                            data-ad-slot="4461304241"
                            data-ad-format="auto"
                            data-full-width-responsive="true"></ins>
                        <script>
                            (adsbygoogle = window.adsbygoogle || []).push({});
                        </script>
                      </iframe>
                    </figure>

                    <figure class="op-ad">
                      <iframe height="300" width="250">
                        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                        <!-- amp_between_article_text_1 -->
                        <ins class="adsbygoogle"
                            style="display:block"
                            data-ad-client="ca-pub-1792676367399829"
                            data-ad-slot="6258791014"
                            data-ad-format="auto"
                            data-full-width-responsive="true"></ins>
                        <script>
                            (adsbygoogle = window.adsbygoogle || []).push({});
                        </script>
                      </iframe>
                    </figure>
                    
                    <footer>
                      <!— Article footer goes here -->
                      <small>Footmali © <?php echo date('Y'); ?></small>
                      <ul class="op-related-articles">
                        <?php $related = false ?>
                        <?php if($related = get_next_article_link($node->nid)): ?>
                        <?php else: ?>
                          <?php $related = get_previous_article_link($node->nid); ?>
                        <?php endif; ?>
                        <li><a href="<?php echo $related; ?>"></a></li>
                      </ul>
                    </footer>
                  </article>
                </body>
              </html>
              ]]>
            </content:encoded>
          </item>
        <?php endforeach; ?>
      </channel>
    </rss>
  <?php
}

function footmali_instant_articles_articles() {
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'article')
        ->propertyCondition('status', NODE_PUBLISHED)
        ->range(0, 10)
        ->propertyOrderBy('created', 'DESC');

  $result = $query->execute();
  $news_items = array();

  if (isset($result['node'])) {
    $news_items_nids = array_keys($result['node']);
    $news_items += entity_load('node', $news_items_nids);
  }

  return $news_items;
}

function footmali_instant_articles_image($style, $imageEntity){
    $variable = array(
        'style_name' => $style,
        'path' => $imageEntity[LANGUAGE_NONE][0]['uri'],
        'width' => $imageEntity[LANGUAGE_NONE][0]['width'],
        'height' => $imageEntity[LANGUAGE_NONE][0]['height'],
    );
    return theme_image_style($variable);
}

function footmali_instant_articles_author($node){
  $author_data = user_load($node->uid);
  $author = $node->name;
  if(isset($author_data->field_first_name) && isset($author_data->field_last_name)){
      $author = field_get_items('user', $author_data, 'field_first_name')[0]['value'] . ' ';
      $author .= field_get_items('user', $author_data, 'field_last_name')[0]['value'];
  }
  return $author;
}

function footmali_instant_articles_category($node){
  $news_category = '';
  $tid = isset($node->field_category[LANGUAGE_NONE][0]['tid']);
  $taxonomy = taxonomy_term_load($tid);
  if($taxonomy){
      $news_category = $taxonomy->name;
  }

  return $news_category;
}

function footmali_instant_articles_trim_paragraph($string, $your_desired_width) {
    $string = strip_tags($string);
    $parts = preg_split('/([\s\n\r]+)/', $string, null, PREG_SPLIT_DELIM_CAPTURE);
    $parts_count = count($parts);
    $length = 0;
    $last_part = 0;
    for (; $last_part < $parts_count; ++$last_part) {
        $length += strlen($parts[$last_part]);
        if ($length > $your_desired_width) { break; }
    }
    return implode(array_slice($parts, 0, $last_part));
}

function get_next_article_link($nid)
{
    $next_article_query = new EntityFieldQuery();
    $next_article_query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'article')
        ->propertyCondition('status', NODE_PUBLISHED, '=')
        ->propertyCondition('nid', $nid, '>')
        ->range(0, 1)
        ->propertyOrderBy('created', 'ASC');

    $next_article_result = $next_article_query->execute();
    $next_article_id = count($next_article_result) > 0 ? array_keys($next_article_result['node']) : false;

    $node = node_load(current($next_article_id));
    $path = 'node/' . $node->nid;

    return $next_article_id ? url($path, array('absolute' => true)) : false;
}

function get_previous_article_link($nid)
{
    $prev_article_query = new EntityFieldQuery();
    $prev_article_query->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', 'article')
        ->propertyCondition('status', NODE_PUBLISHED, '=')
        ->propertyCondition('nid', $nid, '<')
        ->range(0, 1)
        ->propertyOrderBy('created', 'DESC');

    $prev_article_result = $prev_article_query->execute();
    $prev_article_id = count($prev_article_result) ? array_keys($prev_article_result['node']) : false;

    $node = node_load(current($prev_article_id));
    $path = 'node/' . $node->nid;

    return $prev_article_id ? url($path, array('absolute' => true)) : false;
}
